### ISSUE TITLE
Site jump to top of the page every 10-20 seconds

### ISSUE THREAD

**Issue by RainerKi** [screeny05/chrome-harvest-bitbucket#1]
The visible area of the PR page jumps to the top every 10 to 20 seconds after the activation of the time tracking

**Comment by screeny05** [comment]
Which version of Chrome are you using? Are there other Extensions enabled? Is there something logged in the console?

**Comment by screeny05** [comment]
Has been fixed in 1.0.1

**Comment by RainerKi** [comment]
So you don't need my answers anymore?

**Comment by screeny05** [comment]
Na, seems it has been in all Versions. Thank you!
